name: management-groups
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      #with:
        #path: repo
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
   
    - uses: azure/CLI@v1
      with:
        azcliversion: 2.33.0
        inlineScript: |
            az account show
            pwd
            ls
            az deployment tenant what-if --template-file infra-as-code/bicep/modules/managementGroups/managementGroups.bicep --parameters infra-as-code/bicep/modules/managementGroups/managementGroups.parameters.example.json --location eastus